version: 2.1

defaults:
  restore_cache: &restore_cache
    keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

  save_cache: &save_cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  node_8:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - save_cache: *save_cache
      - run: npm test
  node_10_with_percy:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - save_cache: *save_cache
      - run: npm run test-with-percy

workflows:
  version: 2
  test:
    jobs:
      - node_8
      - node_10_with_percy
